name = "bootstrap"
type = "webpack"
account_id = "18ff2b4e6205b938652998cfca0d8cff"
# account_id = ""
workers_dev = true
# routes = [ "agent", "agents" ]
# zone_id = "bootstrap"
# zone_id = ""
webpack_config = "webpack.config.js"
