name = "bootstrap"
type = "webpack"
account_id = "18ff2b4e6205b938652998cfca0d8cff"
# account_id = ""
workers_dev = true
# routes = [ "agent", "agents" ]
# zone_id = "bootstrap"
# zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
 { binding = "BOOTSTRAP", id = "95561bdb2dbc41e8bf6e2975e49a1f6c", preview_id = "30ff63d04cb5433db469a041f67783da" }
]
vars = { ENVIRONMENT = "dev" }

[env.production]
vars = { ENVIRONMENT = "production" }
