name: deploy

on:
 push:
  branches:
   - main

jobs:
 deploy:
  name: deploy
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2

   # Dev deploy.
   - uses: cloudflare/wrangler-action@1.3.0
     with:
      apiToken: ${{ secrets.CF_API_TOKEN }}

   # Prod deploy.
   - uses: cloudflare/wrangler-action@1.3.0
     with:
      apiToken: ${{ secrets.CF_API_TOKEN }}
      environment: 'production'
