name: npm test

on: push

jobs:
 test:
  name: test npm
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node: ['12', '14']

  env:
   CARGO_HOME: ${{ github.workspace }}/.cargo
   CARGO_INSTALL_ROOT: ${{ github.workspace }}/.cargo

  steps:
   # - run: echo "CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}" >> $GITHUB_ENV
   # - run: echo "${CARGO_INSTALL_ROOT}/bin" >> $GITHUB_PATH
   - uses: actions/checkout@v2
   - uses: cloudflare/wrangler-action@1.3.0
     with:
       apiToken: ${{ secrets.CF_API_TOKEN }}
       publish: false
       # preCommands: wrangler build

   # - uses: actions/cache@v2
   #   with:
   #     path: |
   #       ${{ env.CARGO_HOME }}/registry
   #       ${{ env.CARGO_HOME }}/git
   #       ${{ env.CARGO_INSTALL_ROOT }}
   #       target
   #     key: ${{ runner.os }}-cargo-${{ github.ref }}
   # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
   # - run: cargo install wrangler
   - uses: actions/setup-node@v2-beta
     with:
       node-version: ${{ matrix.node }}
   - run: npm install
   - run: wrangler dev &
   - run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8787)" != "200" ]]; do sleep 1 && echo 'waiting for wrangler'; done
   - run: npm test
