name: npm test

on: push

jobs:
 test:
  name: test npm
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node: ['12', '14']

  steps:
   - uses: actions/checkout@v2

   - name: rust cache
     uses: actions/cache@v2
     env:
      cache-name: cache-rust
     with:
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        target
      key: ${{ matrix.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('crates/**/Cargo.toml') }}
      restore-keys: |
       ${{ runner.os }}-cargo-${{ env.cache-name }}-
       ${{ runner.os }}-cargo-
       ${{ runner.os }}-

   - uses: actions-rs/toolchain@v1
     with:
      toolchain: stable
   - run: cargo install wrangler
   - uses: actions/setup-node@v2-beta
     with:
       node-version: ${{ matrix.node }}
   - run: npm install
   # - uses: cloudflare/wrangler-action@1.3.0
   #   with:
   #    apiToken: ${{ secrets.CF_API_TOKEN }}
   #    publish: false
   #    preCommands: wrangler build
   - run: wrangler dev &
   - run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8787)" != "200" ]]; do sleep 1 && echo 'waiting for wrangler'; done
   - run: npm test
